# -*- coding: utf-8 -*-
"""CoPaw Better Discord — Enhanced Discord channel with embed-based thinking threads.

Extends the built-in DiscordChannel with:
  - Embed cards for tool calls (blue), outputs (green), and thinking (purple)
  - Lazy thread creation (only on first tool/thinking event)
  - Persistent typing indicator during agent processing
  - Auto-rename thread with a concise title generated by the agent's LLM
"""
from __future__ import annotations

import asyncio
import json
import logging
import re
from typing import Any, Dict, Optional, Tuple

import discord
from agentscope_runtime.engine.schemas.agent_schemas import MessageType

from copaw.app.channels.discord_.channel import DiscordChannel

logger = logging.getLogger(__name__)

__version__ = "25.0.0"

# ---------------------------------------------------------------------------
# Event-type sets
# ---------------------------------------------------------------------------

_CALL_TYPES = frozenset({
    MessageType.FUNCTION_CALL,
    MessageType.PLUGIN_CALL,
    MessageType.MCP_TOOL_CALL,
})

_OUTPUT_TYPES = frozenset({
    MessageType.FUNCTION_CALL_OUTPUT,
    MessageType.PLUGIN_CALL_OUTPUT,
    MessageType.MCP_TOOL_CALL_OUTPUT,
})

_TOOL_TYPES = _CALL_TYPES | _OUTPUT_TYPES

# ---------------------------------------------------------------------------
# Defaults (overridable via constructor)
# ---------------------------------------------------------------------------

_DEFAULTS = dict(
    embed_color_call=0x60A5FA,       # blue
    embed_color_output=0x34D399,     # green
    embed_color_thinking=0x818CF8,   # indigo
    thread_name="Thinking~",
    thread_auto_archive=60,          # minutes
    max_embed_field_len=900,         # per field value
    max_output_text_len=1800,        # output description (raised for richer output)
    max_call_arg_len=150,            # single-arg display
    typing_interval=8,               # seconds between typing pings
)

# Prompt for thread title generation — language-adaptive, concise
_TITLE_PROMPT = (
    "Based on the following conversation, generate a concise thread title.\n"
    "Rules:\n"
    "1. Detect the primary language used in the conversation and use the same language.\n"
    "2. Keep it brief and descriptive (aim for 4–15 characters/words depending on language).\n"
    "3. No punctuation, quotes, or explanations — return ONLY the title itself.\n\n"
    "User: {user_text}\n"
    "Assistant: {reply_text}"
)


# ---------------------------------------------------------------------------
# Data extraction helpers
# ---------------------------------------------------------------------------

def _extract_text_from_content(value: Any) -> str:
    """Extract plain text from various content formats (str, list of TextContent, object)."""
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple)):
        parts: list[str] = []
        for item in value:
            t = getattr(item, "text", None)
            if isinstance(item, dict):
                t = t or item.get("text")
            if t:
                parts.append(str(t))
        return "\n".join(parts)
    t = getattr(value, "text", None)
    if isinstance(value, dict):
        t = t or value.get("text")
    return str(t) if t else str(value)


def _unwrap_content(data: Any) -> Optional[dict]:
    """Unwrap various content wrapper formats into a plain dict.

    Handles:
      - dict with optional "data" key
      - list of objects with `.data` attribute
      - list of TextContent: [{"type":"text","text":"<json_str>"}]
      - JSON string
      - double-encoded JSON
    """
    if isinstance(data, dict):
        inner = data.get("data", data)
        return inner if isinstance(inner, dict) else None

    if isinstance(data, (list, tuple)):
        # Check for .data attribute pattern
        for item in data:
            d = getattr(item, "data", None)
            if isinstance(d, dict):
                return d
            if isinstance(item, dict) and isinstance(item.get("data"), dict):
                return item["data"]
        # Check for TextContent list: [{"type":"text","text":"<json_str>"}]
        if len(data) == 1:
            item = data[0]
            t = getattr(item, "text", None)
            if isinstance(item, dict):
                t = t or item.get("text")
            if t:
                try:
                    parsed = json.loads(str(t))
                    if isinstance(parsed, dict):
                        return parsed
                except (json.JSONDecodeError, TypeError):
                    pass
        return None

    try:
        parsed = json.loads(str(data))
        if isinstance(parsed, dict):
            return parsed.get("data", parsed)
        if isinstance(parsed, list) and len(parsed) == 1:
            item = parsed[0]
            if isinstance(item, dict) and "text" in item:
                try:
                    return json.loads(item["text"])
                except (json.JSONDecodeError, TypeError):
                    pass
    except (json.JSONDecodeError, TypeError):
        pass
    return None


def _extract_tool_info(content: Any, *, is_output: bool) -> Tuple[Optional[str], Any, Optional[str]]:
    """Return (tool_name, payload, call_id) from event content."""
    data = _unwrap_content(content)
    if not data:
        return None, None, None

    name = data.get("name")
    call_id = data.get("call_id")
    payload = data.get("output") if (is_output and data.get("output") is not None) else data.get("arguments")

    if name or call_id:
        return name, payload, call_id

    # Data itself may be the output (e.g. when content was a TextContent list)
    if is_output:
        return None, data, None
    return None, None, None


# ---------------------------------------------------------------------------
# Embed-field formatting helpers
# ---------------------------------------------------------------------------

def _truncate(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[:limit - 3] + "..."


def _try_parse_json(text: str) -> Any:
    """Try to parse text as JSON, handling markdown code blocks."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        body = lines[1:-1] if lines[-1].strip() == "```" else lines[1:]
        text = "\n".join(body).strip()
    try:
        return json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None


def _payload_to_fields(payload: Any, max_val_len: int = 900) -> Optional[Dict[str, str]]:
    """Convert tool output payload into {key: value} embed fields.

    Handles: list of TextContent, dict, JSON string, plain string.
    Returns None only if payload is completely empty.
    """
    if payload is None:
        return None

    # 1. String payload
    if isinstance(payload, str):
        obj = _try_parse_json(payload)
        if obj is None:
            return {"result": payload}
        payload = obj

    # 2. List of TextContent → extract inner texts
    if isinstance(payload, (list, tuple)):
        texts: list[str] = []
        for item in payload:
            t = getattr(item, "text", None)
            if isinstance(item, dict):
                t = t or item.get("text")
            if t:
                texts.append(str(t))
        if not texts:
            return None
        if len(texts) == 1:
            # Try to parse single text as JSON
            obj = _try_parse_json(texts[0])
            if obj is not None:
                payload = obj
            else:
                return {"result": texts[0]}
        else:
            return {"result": "\n".join(texts)}

    # 3. Dict payload → convert to fields
    if isinstance(payload, dict):
        if not payload:
            return None
        if len(payload) > 30:
            # Too many keys — render as JSON block
            return {"result": json.dumps(payload, ensure_ascii=False, indent=2)}
        fields: Dict[str, str] = {}
        for k, v in payload.items():
            v_str = json.dumps(v, ensure_ascii=False, indent=2) if isinstance(v, (dict, list)) else str(v)
            fields[str(k)] = _truncate(v_str, max_val_len)
        return fields

    # 4. List payload → render as JSON
    if isinstance(payload, list):
        return {"result": json.dumps(payload, ensure_ascii=False, indent=2)}

    return {"result": str(payload)}


# ---------------------------------------------------------------------------
# Channel
# ---------------------------------------------------------------------------

class BetterDiscordChannel(DiscordChannel):
    """Enhanced Discord channel with embed-based thinking threads."""

    channel = "discord"  # replaces built-in discord

    _typing_tasks: Dict[str, asyncio.Task] = {}

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self.color_call: int = kwargs.pop("embed_color_call", _DEFAULTS["embed_color_call"])
        self.color_output: int = kwargs.pop("embed_color_output", _DEFAULTS["embed_color_output"])
        self.color_thinking: int = kwargs.pop("embed_color_thinking", _DEFAULTS["embed_color_thinking"])
        self.thread_name: str = kwargs.pop("thread_name", _DEFAULTS["thread_name"])
        self.thread_auto_archive: int = kwargs.pop("thread_auto_archive", _DEFAULTS["thread_auto_archive"])
        self.max_field_len: int = kwargs.pop("max_embed_field_len", _DEFAULTS["max_embed_field_len"])
        self.max_output_len: int = kwargs.pop("max_output_text_len", _DEFAULTS["max_output_text_len"])
        self.max_call_arg_len: int = kwargs.pop("max_call_arg_len", _DEFAULTS["max_call_arg_len"])
        self.typing_interval: int = kwargs.pop("typing_interval", _DEFAULTS["typing_interval"])

        super().__init__(*args, **kwargs)

        self._active_thread_id: Optional[str] = None
        self._active_channel_id: Optional[str] = None
        self._active_user_text: Optional[str] = None
        self._active_reply_text: Optional[str] = None

        logger.info("CoPaw Better Discord v%s initialized", __version__)

    # ------------------------------------------------------------------
    # Lifecycle hooks
    # ------------------------------------------------------------------

    async def _before_consume_process(self, request: Any) -> None:
        await super()._before_consume_process(request)
        cid = self._get_channel_id(request)
        if cid:
            self._active_channel_id = cid
            self._start_typing(cid)
        # Collect last user message text for thread title generation
        msgs = getattr(request, "input", None) or []
        for msg in reversed(msgs):
            if getattr(msg, "role", None) == "user":
                self._active_user_text = _extract_text_from_content(getattr(msg, "content", ""))
                break

    async def _on_process_completed(self, request: Any, to_handle: str, send_meta: Dict[str, Any]) -> None:
        self._stop_typing(self._active_channel_id)
        # Fire-and-forget thread rename before clearing state
        if self._active_thread_id and (self._active_user_text or self._active_reply_text):
            asyncio.create_task(self._rename_thread(
                self._active_thread_id,
                self._active_user_text or "",
                self._active_reply_text or "",
            ))
        self._active_thread_id = None
        self._active_channel_id = None
        self._active_user_text = None
        self._active_reply_text = None
        await super()._on_process_completed(request, to_handle, send_meta)

    async def _on_consume_error(self, request: Any, to_handle: str, err_text: str) -> None:
        self._stop_typing(self._active_channel_id)
        self._active_thread_id = None
        self._active_channel_id = None
        self._active_user_text = None
        self._active_reply_text = None
        await super()._on_consume_error(request, to_handle, err_text)

    # ------------------------------------------------------------------
    # Typing indicator
    # ------------------------------------------------------------------

    async def _typing_loop(self, channel_id: str) -> None:
        route = discord.http.Route("POST", "/channels/{channel_id}/typing", channel_id=int(channel_id))
        try:
            while True:
                try:
                    await self._client.http.request(route)
                except Exception:
                    pass
                await asyncio.sleep(self.typing_interval)
        except asyncio.CancelledError:
            pass

    def _start_typing(self, channel_id: str) -> None:
        if not channel_id:
            return
        existing = self._typing_tasks.get(channel_id)
        if existing and not existing.done():
            return
        self._typing_tasks[channel_id] = asyncio.create_task(self._typing_loop(channel_id))

    def _stop_typing(self, channel_id: Optional[str]) -> None:
        if not channel_id:
            return
        task = self._typing_tasks.pop(channel_id, None)
        if task and not task.done():
            task.cancel()

    # ------------------------------------------------------------------
    # Event interception
    # ------------------------------------------------------------------

    async def on_event_message_completed(
        self, request: Any, to_handle: str, event: Any, send_meta: Dict[str, Any],
    ) -> None:
        msg_type = getattr(event, "type", None)
        event_content = getattr(event, "content", "")

        # Capture assistant reply text for thread title generation
        if msg_type == "message":
            text = _extract_text_from_content(event_content)
            if text:
                self._active_reply_text = text
            return await super().on_event_message_completed(request, to_handle, event, send_meta)

        if msg_type not in _TOOL_TYPES and msg_type != MessageType.REASONING:
            return await super().on_event_message_completed(request, to_handle, event, send_meta)

        thread_id = await self._ensure_thread(request)
        if not thread_id:
            return await super().on_event_message_completed(request, to_handle, event, send_meta)

        embed = self._build_embed(event)
        if embed:
            await self._send_to_thread(thread_id, embed=embed)
        else:
            text = self._build_fallback_text(event)
            if text:
                await self._send_to_thread(thread_id, text=text)
            else:
                await super().on_event_message_completed(request, to_handle, event, send_meta)

    # ------------------------------------------------------------------
    # Thread management
    # ------------------------------------------------------------------

    async def _ensure_thread(self, request: Any) -> Optional[str]:
        """Return existing thread id, or create one lazily."""
        if self._active_thread_id:
            return self._active_thread_id

        meta = getattr(request, "channel_meta", {}) or {}
        cid, mid = meta.get("channel_id"), meta.get("message_id")
        if not cid or not mid:
            return None

        try:
            channel = self._client.get_channel(int(cid)) or await self._client.fetch_channel(int(cid))
            msg = await channel.fetch_message(int(mid))
            thread = await msg.create_thread(
                name=self.thread_name,
                auto_archive_duration=self.thread_auto_archive,
            )
            self._active_thread_id = str(thread.id)
            return self._active_thread_id
        except Exception:
            logger.warning("Failed to create thread in channel %s", cid, exc_info=True)
            return None

    async def _send_to_thread(
        self, thread_id: str, *, embed: Optional[discord.Embed] = None, text: str = "",
    ) -> None:
        try:
            target = self._client.get_channel(int(thread_id)) or await self._client.fetch_channel(int(thread_id))
            if embed:
                await target.send(embed=embed)
            else:
                for i in range(0, len(text), 2000):
                    await target.send(text[i:i + 2000])
        except Exception:
            logger.warning("Failed to send to thread %s", thread_id, exc_info=True)

    async def _generate_thread_title(self, user_text: str, reply_text: str) -> Optional[str]:
        """Generate a concise thread title using the agent's current LLM.

        Detects the conversation language automatically and uses the same language.
        Falls back silently on any error.
        """
        try:
            from copaw.providers.provider_manager import ProviderManager  # type: ignore
            model = ProviderManager.get_active_chat_model()
        except Exception:
            logger.debug("ProviderManager not available for thread title", exc_info=True)
            return None

        prompt = _TITLE_PROMPT.format(
            user_text=user_text[:300],
            reply_text=reply_text[:400],
        )

        original_stream = getattr(model, "stream", None)
        try:
            model.stream = False
            resp = await model([{"role": "user", "content": prompt}])
        except Exception:
            logger.debug("LLM call for thread title failed", exc_info=True)
            return None
        finally:
            if original_stream is not None:
                model.stream = original_stream

        # Parse ChatResponse: content may be list of {type, text} or plain string
        content = resp.get("content") if hasattr(resp, "get") else getattr(resp, "content", "")
        if isinstance(content, list):
            texts = [c.get("text", "") for c in content if isinstance(c, dict) and c.get("type") == "text"]
            content = "".join(texts)
        title = str(content or "").strip()
        # Discord thread name: 1-100 chars
        title = re.sub(r"\s+", " ", title)[:100].strip()
        return title or None

    async def _rename_thread(self, thread_id: str, user_text: str, reply_text: str) -> None:
        """Generate a concise title and rename the Discord thread. Silently ignores failures."""
        title = await self._generate_thread_title(user_text, reply_text)
        if not title:
            return

        try:
            route = discord.http.Route(
                "PATCH", "/channels/{channel_id}", channel_id=int(thread_id)
            )
            await self._client.http.request(route, json={"name": title})
            logger.info("Thread %s renamed → %s", thread_id, title)
        except Exception:
            logger.warning("Failed to rename thread %s", thread_id, exc_info=True)

    # ------------------------------------------------------------------
    # Embed builders
    # ------------------------------------------------------------------

    def _build_embed(self, event: Any) -> Optional[discord.Embed]:
        msg_type = getattr(event, "type", None)
        content = getattr(event, "content", "")

        if msg_type in _CALL_TYPES:
            return self._build_call_embed(content)
        if msg_type in _OUTPUT_TYPES:
            return self._build_output_embed(content)
        if msg_type == MessageType.REASONING:
            return self._build_thinking_embed(content)
        return None

    def _build_call_embed(self, content: Any) -> discord.Embed:
        name, payload, _ = _extract_tool_info(content, is_output=False)
        embed = discord.Embed(title=f"⚡ {name or 'unknown'}", color=self.color_call)

        if payload is not None:
            args = self._payload_to_call_fields(payload)
            for k, v in args.items():
                embed.add_field(name=k, value=_truncate(v, self.max_field_len), inline=True)

        return embed

    def _build_output_embed(self, content: Any) -> Optional[discord.Embed]:
        name, payload, _ = _extract_tool_info(content, is_output=True)
        embed = discord.Embed(title=f"✅ {name or 'unknown'}", color=self.color_output)

        fields = _payload_to_fields(payload, max_val_len=self.max_field_len)
        if not fields:
            return None

        for k, v in fields.items():
            # Wrap JSON-like values in a code block for readability
            if len(fields) == 1 and len(v) > 100:
                embed.description = _truncate(v, self.max_output_len)
            else:
                embed.add_field(name=k, value=_truncate(v, self.max_field_len), inline=False)

        return embed

    def _build_thinking_embed(self, content: Any) -> Optional[discord.Embed]:
        text = _extract_text_from_content(content).strip()
        if not text:
            return None

        original_len = len(text)
        truncated = text[:self.max_output_len - 3] + "..." if original_len > self.max_output_len else text
        truncated = re.sub(r"\n{3,}", "\n\n", truncated)

        embed = discord.Embed(title="💭 Thinking", color=self.color_thinking, description=truncated)
        if original_len > self.max_output_len:
            embed.set_footer(text=f"truncated ({original_len} chars)")
        return embed

    def _build_fallback_text(self, event: Any) -> str:
        """Plain-text fallback when embed construction returns None."""
        msg_type = getattr(event, "type", None)
        name, payload, _ = _extract_tool_info(
            getattr(event, "content", ""),
            is_output=msg_type in _OUTPUT_TYPES,
        )
        label = name or "unknown"
        text = _extract_text_from_content(payload)

        if msg_type in _CALL_TYPES:
            return f"⚡ **{label}**\n{_truncate(text, self.max_call_arg_len)}"
        if msg_type in _OUTPUT_TYPES:
            return f"✅ **{label}**\n{_truncate(text, self.max_output_len)}"
        if msg_type == MessageType.REASONING:
            text = _extract_text_from_content(getattr(event, "content", "")).strip()
            return f"💭 **Thinking**\n{_truncate(text, self.max_output_len)}"
        return ""

    # ------------------------------------------------------------------
    # Helper: call argument fields
    # ------------------------------------------------------------------

    def _payload_to_call_fields(self, payload: Any) -> Dict[str, str]:
        """Convert call arguments to {key: value} dict for embed fields."""
        if isinstance(payload, str):
            try:
                payload = json.loads(payload)
            except (json.JSONDecodeError, TypeError):
                return {"args": payload}
        if isinstance(payload, dict) and payload:
            return {k: (v if isinstance(v, str) else json.dumps(v, ensure_ascii=False)) for k, v in payload.items()}
        return {}

    # ------------------------------------------------------------------
    # Utility
    # ------------------------------------------------------------------

    @staticmethod
    def _get_channel_id(request: Any) -> Optional[str]:
        meta = getattr(request, "channel_meta", {}) or {}
        return meta.get("channel_id")
